/// Flutter icons BrandIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BrandIcons
///      fonts:
///       - asset: fonts/BrandIcons.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class BrandIcons {
  BrandIcons._();

  static const _kFontFam = 'BrandIcons';
  static const String? _kFontPkg = null;

  static const IconData css3 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dart = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData digitalocean = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discord = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData figma = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData firebase = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flutter = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData github = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData html5 = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ionos = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData java = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData javascript = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kotlin = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microsoftteams = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mongodb = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mysql = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData php = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData postman = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData react = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skype = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slack = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData typescript = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData visualstudiocode = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData xcode = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adobexd = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData android = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clickup = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clockify = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData csharp = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData python = IconData(0xf3e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
